var testData =[
  {
    "ID":2844,
    "title":"Article Title",
    "status":"publish",
    "type":"post",
    "author":{
      "ID":4,
      "username":"Apple",
      "name":"Apple Bananas",
      "first_name":"Apple",
      "last_name":"Bananas",
      "nickname":"Apple",
      "slug":"Apple",
      "URL":"",
      "avatar":"url",
      "description":"",
      "registered":"2019-01-01T12:49:25+00:00",
      "meta":{
        "links":{
          "self":"url",
          "archives":"url"
        }
      }
    },
    "content":"<p style=\"text-align: justify;\"><\/p>",
    "parent":0,
    "link":"url",
    "date":"2019-01-25T13:04:03+00:00",
    "modified":"2019-01-26T13:54:06+00:00",
    "format":"standard",
    "slug":"what is a slug",
    "guid":"url",
    "excerpt":"<p>Excerpt<\/p>\n",
    "menu_order":0,
    "comment_status":"open",
    "ping_status":"open",
    "sticky":false,
    "date_tz":"UTC",
    "date_gmt":"2019-01-25T13:04:03+00:00",
    "modified_tz":"UTC",
    "modified_gmt":"2019-01-26T13:54:06+00:00",
    "meta":{
      "links":{
        "self":"url",
        "author":"url",
        "collection":"url",
        "replies":"url",
        "version-history":"url"
      }
    },
    "order":18,
    "featured_image":{
      "ID":2846,
      "title":"image title",
      "status":"inherit",
      "type":"attachment",
      "author":{
        "ID":4,
        "username":"Apple",
        "name":"Apple Bananas",
        "first_name":"Apple",
        "last_name":"Bananas",
        "nickname":"Apple",
        "slug":"Apple",
        "URL":"",
        "avatar":"url",
        "description":"",
        "registered":"2015-10-08T12:49:25+00:00",
        "meta":{
          "links":{
            "self":"url",
            "archives":"url"
          }
        }
      },
      "content":"<p class=\"attachment\"><a href='testData\/myimage.png'><img width=\"559\" height=\"373\" src=\"testData\/myimage.png\" class=\"attachment-medium\" alt=\"myimage\" \/><\/a><\/p>\n",
      "parent":2844,
      "link":"url",
      "date":"2019-01-25T13:00:28+00:00",
      "modified":"2019-01-25T13:00:28+00:00",
      "format":"standard",
      "slug":"myimage",
      "guid":"testData\/myimage.png",
      "excerpt":null,
      "menu_order":0,
      "comment_status":"open",
      "ping_status":"open",
      "sticky":false,
      "date_tz":"UTC",
      "date_gmt":"2019-01-25T13:00:28+00:00",
      "modified_tz":"UTC",
      "modified_gmt":"2019-01-25T13:00:28+00:00",
      "meta":{
        "links":{
          "self":"url",
          "author":"url",
          "collection":"url",
          "replies":"url",
          "version-history":"url",
          "up":"url"
        }
      },
      "order":999,
      "terms":[

      ],
      "source":"testData\/myimage.png",
      "is_image":true,
      "attachment_meta":{
        "width":559,
        "height":373,
        "file":"2019\/01\/myimage.png",
        "sizes":{
          "thumbnail":{
            "file":"myimage-150x100.png",
            "width":150,
            "height":100,
            "mime-type":"image\/png",
            "url":"testData\/myimage-150x100.png"
          },
          "post-thumbnail":{
            "file":"myimage-559x372.png",
            "width":559,
            "height":372,
            "mime-type":"image\/png",
            "url":"testData\/myimage-559x372.png"
          }
        },
        "image_meta":{
          "aperture":0,
          "credit":"",
          "camera":"",
          "caption":"",
          "created_timestamp":0,
          "copyright":"",
          "focal_length":0,
          "iso":0,
          "shutter_speed":0,
          "title":""
        }
      }
    },
    "terms":{
      "category":[
        {
          "ID":24,
          "name":"2019 - January",
          "slug":"2019-january",
          "description":"",
          "parent":null,
          "count":27,
          "link":"url",
          "meta":{
            "links":{
              "collection":"url",
              "self":"url"
            }
          }
        }
      ],
      "post_tag":[
        {
          "ID":10,
          "name":"social",
          "slug":"social",
          "description":"",
          "parent":null,
          "count":22,
          "link":"url",
          "meta":{
            "links":{
              "collection":"url",
              "self":"url"
            }
          }
        },
        {
          "ID":3,
          "name":"WhatsHappening",
          "slug":"whatsup",
          "description":"",
          "parent":null,
          "count":101,
          "link":"url",
          "meta":{
            "links":{
              "collection":"url",
              "self":"url"
            }
          }
        }
      ]
    }
  }
];